# Generated by Django 5.2.7 on 2025-10-28 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_basement'),
    ]

    operations = [
        migrations.AddField(
            model_name='basement',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
