# Generated by Django 5.2.7 on 2025-10-28 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_basement_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basement',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
