# Generated by Django 5.2.7 on 2025-10-28 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_basement_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basement',
            name='image',
        ),
    ]
