# Generated by Django 5.2.7 on 2025-10-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home_name_ar_home_name_en_home_name_ru_home_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='description_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
