# Generated by Django 5.2.7 on 2025-10-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_description_ar_home_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='pricePerSqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
