# Generated by Django 5.2.7 on 2025-10-29 03:50

import django.core.validators
import django.db.models.deletion
import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_home_price_alter_home_pricepersqm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='basement/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP', 'heic', 'heif']), home.models.check_image_size])),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.home')),
            ],
            options={
                'verbose_name': 'Basement image',
                'verbose_name_plural': 'Basement images',
                'db_table': 'basementimage',
            },
        ),
    ]
