# Generated by Django 5.2.7 on 2025-10-29 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_basementimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basementimage',
            name='home',
        ),
        migrations.AddField(
            model_name='basementimage',
            name='basement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.basement'),
        ),
        migrations.AlterField(
            model_name='basement',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
