# Generated by Django 5.2.7 on 2025-10-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_basementimage_home_basementimage_basement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('entrance', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='entrance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='home_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='totalarea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='commonhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.commonhouse'),
        ),
    ]
