# Generated by Django 5.2.7 on 2025-10-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_home_status_home_status_ar_home_status_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonhouse',
            name='entrance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
