# Generated by Django 5.2.7 on 2025-10-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_commonhouse_entrance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='home_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
