# Generated by Django 5.2.7 on 2025-10-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_home_home_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='buildingBlock',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
