# Generated by Django 5.2.7 on 2025-10-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_home_buildingblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='yearBuilt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
