# Generated by Django 5.2.7 on 2025-10-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_home_yearbuilt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='commonhouse',
        ),
        migrations.RemoveField(
            model_name='qualities',
            name='home',
        ),
        migrations.AddField(
            model_name='home',
            name='qualities',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='qualities_ar',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='qualities_en',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='qualities_ru',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='qualities_uz',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='qualities_zh_hans',
            field=models.JSONField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='CommonHouse',
        ),
        migrations.DeleteModel(
            name='Qualities',
        ),
    ]
