# Generated by Django 5.2.7 on 2025-10-30 11:52

import django.core.validators
import django.db.models.deletion
import utils.compressor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_home_commonhouse_remove_qualities_home_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('handover', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='commonhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.commonhouse'),
        ),
        migrations.CreateModel(
            name='CommonHouseAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('blocks', models.IntegerField(default=0)),
                ('apartments', models.IntegerField(default=0)),
                ('phases', models.IntegerField(default=0)),
                ('projectarea', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('commonhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.commonhouse')),
            ],
        ),
        migrations.CreateModel(
            name='CommonHouseAboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commonaboutimage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP', 'heic', 'heif']), utils.compressor.check_image_size])),
                ('commonhouseabout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.commonhouseabout')),
            ],
        ),
        migrations.CreateModel(
            name='CommonHouseAdvImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commonadvimage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP', 'heic', 'heif']), utils.compressor.check_image_size])),
                ('commonhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.commonhouse')),
            ],
        ),
        migrations.CreateModel(
            name='CommonHouseMainImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='commonmainimage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP', 'heic', 'heif']), utils.compressor.check_image_size])),
                ('commonhouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.commonhouse')),
            ],
        ),
    ]
