# Generated by Django 5.2.7 on 2025-10-30 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_commonhouse_home_commonhouse_commonhouseabout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonhouse',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonhouse',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
