# Generated by Django 5.2.7 on 2025-10-31 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_commonhouse_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonhouse',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='description_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='description_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='title_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='title_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonhouse',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='apartments_ar',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='apartments_en',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='apartments_ru',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='apartments_uz',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='apartments_zh_hans',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='description_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='commonhouseabout',
            name='description_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
