# Generated by Django 5.2.7 on 2025-10-31 10:01

import django.core.validators
import django.db.models.deletion
import utils.compressor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_basement_area_alter_basement_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_uz', models.CharField(max_length=100, null=True)),
                ('title_en', models.CharField(max_length=100, null=True)),
                ('title_ru', models.CharField(max_length=100, null=True)),
                ('title_zh_hans', models.CharField(max_length=100, null=True)),
                ('title_ar', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('progress', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('stage_uz', models.CharField(blank=True, max_length=100, null=True)),
                ('stage_en', models.CharField(blank=True, max_length=100, null=True)),
                ('stage_ru', models.CharField(blank=True, max_length=100, null=True)),
                ('stage_zh_hans', models.CharField(blank=True, max_length=100, null=True)),
                ('stage_ar', models.CharField(blank=True, max_length=100, null=True)),
                ('overdate', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InProgressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inprogress/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP', 'heic', 'heif']), utils.compressor.check_image_size])),
                ('inprogress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.inprogress')),
            ],
        ),
    ]
