# Generated by Django 5.2.7 on 2025-10-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_inprogress_inprogressimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='totalarea',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='home',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
