# Generated by Django 5.2.7 on 2025-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_home_totalarea_alter_home_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='inprogress',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='description_ar',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='description_en',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='description_ru',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='description_uz',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inprogress',
            name='description_zh_hans',
            field=models.CharField(blank=True, null=True),
        ),
    ]
