# Generated by Django 5.2.7 on 2025-11-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_inprogress_description_inprogress_description_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='overDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
