# Generated by Django 5.2.7 on 2025-11-03 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_home_overdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('description_uz', models.CharField(blank=True, max_length=250, null=True)),
                ('description_en', models.CharField(blank=True, max_length=250, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=250, null=True)),
                ('description_zh_hans', models.CharField(blank=True, max_length=250, null=True)),
                ('description_ar', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='downpayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.downpayment'),
        ),
    ]
