# Generated by Django 5.2.7 on 2025-11-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_downpayment_home_downpayment'),
        ('utils', '0013_delete_downpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='downpayment',
        ),
        migrations.AddField(
            model_name='downpayment',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.homepage'),
        ),
    ]
