# Generated by Django 5.2.7 on 2025-11-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_home_downpayment_downpayment_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='downpayment',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.home'),
        ),
    ]
