# Generated by Django 5.2.7 on 2025-11-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_downpayment_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
