# Generated by Django 5.2.7 on 2025-11-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_home_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
