# Generated by Django 5.2.7 on 2025-11-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_alter_home_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='entrance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
