# Generated by Django 5.2.7 on 2025-11-12 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_alter_home_entrance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonhouseabout',
            name='apartments_ar',
        ),
        migrations.RemoveField(
            model_name='commonhouseabout',
            name='apartments_en',
        ),
        migrations.RemoveField(
            model_name='commonhouseabout',
            name='apartments_ru',
        ),
        migrations.RemoveField(
            model_name='commonhouseabout',
            name='apartments_uz',
        ),
        migrations.RemoveField(
            model_name='commonhouseabout',
            name='apartments_zh_hans',
        ),
    ]
