# Generated by Django 5.2.7 on 2025-11-17 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_remove_commonhouseabout_apartments_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basement',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basement', to='home.home'),
        ),
    ]
