# Generated by Django 5.2.7 on 2025-10-29 04:37

import django.core.validators
import django.db.models.deletion
import utils.compressor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('title_uz', models.CharField(blank=True, max_length=120, null=True)),
                ('title_en', models.CharField(blank=True, max_length=120, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=120, null=True)),
                ('title_zh_hans', models.CharField(blank=True, max_length=120, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('description_uz', models.TextField(blank=True, max_length=500, null=True)),
                ('description_en', models.TextField(blank=True, max_length=500, null=True)),
                ('description_ru', models.TextField(blank=True, max_length=500, null=True)),
                ('description_zh_hans', models.TextField(blank=True, max_length=500, null=True)),
                ('description_ar', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='homepageimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='homepageimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(upload_to='homepage/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP', 'heic', 'heif']), utils.compressor.check_image_size]),
        ),
        migrations.AddField(
            model_name='homepageimage',
            name='homepage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.homepage'),
        ),
    ]
