# Generated by Django 5.2.7 on 2025-10-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0003_advertisementbanner_advertisementbannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementbanner',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='description_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='description_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='title_ar',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='title_en',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='title_ru',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='title_uz',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='advertisementbanner',
            name='title_zh_hans',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
