# Generated by Django 5.2.7 on 2025-10-31 10:16

import django.core.validators
import utils.compressor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_advertisementbanner_description_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('text_uz', models.TextField(blank=True, max_length=500, null=True)),
                ('text_en', models.TextField(blank=True, max_length=500, null=True)),
                ('text_ru', models.TextField(blank=True, max_length=500, null=True)),
                ('text_zh_hans', models.TextField(blank=True, max_length=500, null=True)),
                ('text_ar', models.TextField(blank=True, max_length=500, null=True)),
                ('full_name', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(upload_to='reviews/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp', 'JPG', 'JPEG', 'PNG', 'SVG', 'WEBP', 'heic', 'heif']), utils.compressor.check_image_size])),
            ],
        ),
    ]
