# Generated by Django 5.2.7 on 2025-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('experience', models.CharField(blank=True, max_length=100, null=True)),
                ('obyects', models.CharField(blank=True, max_length=100, null=True)),
                ('guarantee', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
