# Generated by Django 5.2.7 on 2025-10-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_aboutcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutcompany',
            name='description_ar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='description_en',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='description_ru',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='description_uz',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='aboutcompany',
            name='description_zh_hans',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
