# Generated by Django 5.2.7 on 2025-10-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0010_aboutcompany_description_ar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutcompany',
            old_name='obyects',
            new_name='ourobjects',
        ),
    ]
