# Generated by Django 5.2.7 on 2025-11-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_rename_obyects_aboutcompany_ourobjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True)),
            ],
        ),
    ]
