# Generated by Django 5.2.7 on 2025-11-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_downpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DownPayment',
        ),
    ]
