# Generated by Django 5.2.7 on 2025-11-05 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_delete_downpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('address_uz', models.CharField(max_length=100, null=True)),
                ('address_en', models.CharField(max_length=100, null=True)),
                ('address_ru', models.CharField(max_length=100, null=True)),
                ('address_zh_hans', models.CharField(max_length=100, null=True)),
                ('address_ar', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('description_uz', models.CharField(blank=True, max_length=500, null=True)),
                ('description_en', models.CharField(blank=True, max_length=500, null=True)),
                ('description_ru', models.CharField(blank=True, max_length=500, null=True)),
                ('description_zh_hans', models.CharField(blank=True, max_length=500, null=True)),
                ('description_ar', models.CharField(blank=True, max_length=500, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
